project_id = "zbfqybhucxxfjgihrmpg"

[functions.get-podcast-asset]
verify_jwt = false

[functions.get-spotify-album-art]
verify_jwt = false

[functions.get-schedule]
verify_jwt = false

[functions.send-request]
verify_jwt = false

[functions.search-spotify]
verify_jwt = false

[functions.setup-admin]
verify_jwt = false